# Set update schedule for GitHub Actions
---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "fix: "
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "fix: "
