---

name: check-yaml
on: [pull_request]
jobs:
  check-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bewuethr/yamllint-action@v1
        with:
          config-file: .yamllint
