---

name: 'Release'

on:
  release:
    types: [published]

permissions:
  contents: write  # upload release assets
  id-token: write  # aws auth

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      ref: ${{ github.ref_name }}
    secrets: inherit

  render-task-definition:
    uses: ./.github/workflows/render-task-definition.yml
    with:
      ref: ${{ github.ref_name }}
    secrets: inherit

  register-task-definition:
    name: 'Register task definition'
    needs:
      - build-docker-image
      - render-task-definition
    uses: shopsmart/github-actions/.github/workflows/register-task-definition.yml@v4
    with:
      role-name: ${{ vars.APPLICATION }}-deploy
      task-definition-tags: version=${{ github.ref_name }}
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
